lecture3
yosukeshimizu24/RaiseTech pull request #6
Opened 2024-02-10 08:56 UTC by yosukeshimizu24

lecture3の課題提出になります。
ご確認のほどよろしくい願いいたします。

2024-02-11 15:26 UTC, MasatoshiMizumoto requested changes
Discordでも連絡しましたが、すべての画像が表示されていないので、そちらで表示が確認できることを済ませてからまたご連絡ください！

2024-02-12 06:10 UTC, MasatoshiMizumoto requested changes
まだ一部スタイル崩れがあるので確認お願いします！

2024-02-12 06:10 UTC, MasatoshiMizumoto commented on lecture3-2.md
> +-まずmySQLを停止させようと「sudo service mysql stop」を入力したところ停止されなかったが、「sudo service mysqld stop」を入力すると停止した。なぜmysqlのあとにｄをつけると反映
ここより後のスタイルが認識されてないようですね！
```suggestion
- まずmySQLを停止させようと「sudo service mysql stop」を入力したところ停止されなかったが、「sudo service mysqld stop」を入力すると停止した。なぜmysqlのあとにｄをつけると反映
```

2024-02-12 06:20 UTC, yosukeshimizu24 commented on lecture3-2.md
> +-まずmySQLを停止させようと「sudo service mysql stop」を入力したところ停止されなかったが、「sudo service mysqld stop」を入力すると停止した。なぜmysqlのあとにｄをつけると反映
訂正しました。
ご確認よろしくお願いします。

2024-02-12 07:48 UTC, MasatoshiMizumoto approved these changes
LGTMです！

2024-02-12 08:21 UTC, merged